export const Clist = [
    {
        id:0,
        image:"./images/Scenery1.jpg",
        title:"Sheron",
    },
    {
        id:1,
        image:"./images/Scenery2.jpg",
        title:"KettleMan",
    },
    {
        id:2,
        image:"./images/Scenery3.jpg",
        title:"Mansi",
    },
    {
        id:3,
        image:"./images/Scenery4.jpg",
        title:"HelpMe",
    },
];