# Generated by Django 5.1.2 on 2024-11-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_customer_show_theater_performance_ticket_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
